version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: sanic server.sanic_app.app --auto-reload  --host 0.0.0.0 --port 8000