version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
       - FLASK_DEBUG=1
       - FLASK_ENV=development
    command: flask run --host 0.0.0.0 --port 8000
    networks:
      - json2dataclass_default
networks:
   json2dataclass_default:
     driver: bridge
     external: true
